### ISSUE TITLE
Комментарии

### ISSUE THREAD

**Issue by apredeus** [alnfedorov/nanopore-hw#9]
Привет! Отличная работа, мне очень понравилось то, что вы сделали. Значительно больше, чем я просил, и все со смыслом - молодцы. 

Замечания:

- MinIONQC у вас не завелся, потому что он использует не fastq, а специальный технический файл, который получается при бейсколлинге, *sequencing_summary.txt*. У вас его не было, потому запустить его не было шанса :)
- Не стоило смешивать длинные и короткие риды в один репорт MultiQС. Вообще, FastQC бессмысленно применять для длинных прочтений - почти все его функции будут работать на них неправильно, т.к. рассчитаны на короткие прочтения. 
- Можно было проверить на адаптеры и короткие прочтения (там они могут навредить сборке гораздо больше). Для этого очень хорош [bbduk](https://jgi.doe.gov/data-and-tools/bbtools/bb-tools-user-guide/bbduk-guide/).
- При запуске `abricate` я просил использовать *все базы*, а вы запустили только с дефолтной (ncbi). Если использовать, например, базу данных CARD, то находится больше генов резистентности. 

В остальном - прекрасная работа, поздравляю.

**Comment by alnfedorov** [comment]
Добрый вечер!

* Действительно, вопрос про sequencing_summary.txt мы как-то очень сильно проморгали 🤦
* У нас не завелся MinIONQC, мы решили хоть как-то посмотреть на наши длинные риды. Но в целом, абсолютно точное замечание.
* Спасибо за совет про bbduk, надо будет его попробовать.

Спасибо за отзыв и науку, было классно :)
